# Generated by Django 4.2.7 on 2024-01-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
