# Generated by Django 4.2.7 on 2024-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='tur',
            field=models.ManyToManyField(null=True, to='movie.tur'),
        ),
    ]
