# Generated by Django 4.2.7 on 2024-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_izlenenler'),
    ]

    operations = [
        migrations.AddField(
            model_name='izlenenler',
            name='izlenen',
            field=models.ManyToManyField(to='movie.movies'),
        ),
    ]
